apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-server
  labels:
    app: fast-api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-api-server
  template:
    metadata:
      labels:
        app: fast-api-server
    spec:
      containers:
      - name: fast-api-server
        image: biz4grouptest138/fast-api-server:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_POzaJCNsI9W0@ep-dark-frost-adl6b3cj-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
        - name: SECRET_KEY
          value: "supersecretkey123456789abcdefghijklmnopqrstuvwxyz"
