apiVersion: v1
kind: Pod
metadata:
  name: fast-api-server
spec:
  containers:
  - name: fast-api-server
    image: biz4grouptest138/fast-api-server:v1
    ports:
      - containerPort: 8000
    envFrom:
      - secretRef:
          name: fast-api-secrets 