name: CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: self-hosted   # Uses your EC2 GitHub runner

    env:                   # Set environment variables for all steps
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Python version
        run: python3.12 --version 

      - name: Install dependencies
        run: |
          python3.12 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest || true   # allow pipeline to continue even if tests fail

      - name: Restart FastAPI with Gunicorn
        run: |
          pkill -f "gunicorn" || true
          nohup ./venv/bin/gunicorn app.main:app --workers 4 --bind 0.0.0.0:8000 --daemon 
