name: CI/CD Pipeline

on:
  push:
    branches: ["main","master"]

jobs:
  deploy:
    runs-on: self-hosted   # uses EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest || true   # skip failing tests if needed

      - name: Restart FastAPI with Gunicorn
        run: |
          pkill -f "gunicorn" || true
          nohup ./venv/bin/gunicorn app.main:app --workers 4 --bind 0.0.0.0:8000 --daemon &
