name: CI/CD Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Python version
        run: python3.12 --version 

      - name: Install dependencies in persistent venv
        run: |
          /home/ubuntu/actions-runner/_work/fast-api-server/fast-api-server/venv/bin/pip install --upgrade pip
          /home/ubuntu/actions-runner/_work/fast-api-server/fast-api-server/venv/bin/pip install -r requirements.txt

      - name: Run tests
        run: |
          /home/ubuntu/actions-runner/_work/fast-api-server/fast-api-server/venv/bin/pytest || true

      - name: Restart FastAPI service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart fastapi
          sudo systemctl status fastapi --no-pager
          # sudo journalctl -u fastapi --no-pager -n 10
